name: Rust

on:
  pull_request:
  push:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/install@v0.1
      with:
        crate: wasm-pack
        version: latest
        use-tool-cache: true
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run miri tests
      run: cargo miri test --verbose
    - name: Run wasm tests
      run: cd rkyv_test && wasm-pack test --node -- --features "wasm"
